name: isolate_json_parser
description: "Isolate Json Parser"
version: 0.0.2
homepage: https://delizondo.com
repository: https://github.com/delizondo/IsolateJsonParser

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
