name: isolate_json_parser_generator
description: "A new Flutter package project."
version: 0.0.2
homepage: https://delizondo.com
repository: https://github.com/delizondo/IsolateJsonParser

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.1
  source_gen: ^1.5.0
  build_config: ^1.1.1
  code_builder: ^4.10.0
  glob: ^2.1.2
  dart_style: ^2.3.7
  isolate_json_parser: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
