name: isolate_json_parser_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  isolate_json_parser: ^0.0.4
  dio: ^5.6.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  isolate_json_parser_generator: ^0.0.4

flutter:
  uses-material-design: true
